language: rust
sudo: false

rust:
  - 1.10.0
  - 1.11.0
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev

before_script:
- pip install 'travis-cargo<0.2' --user
- export PATH=$HOME/.local/bin:$PATH

script:
- (cd quasi && travis-cargo --skip nightly test -- --features with-syntex)
- (cd quasi && travis-cargo doc -- --features with-syntex)
- (cd quasi && travis-cargo --only nightly test -- --features "with-syntex unstable-testing")
- (cd quasi && travis-cargo --only nightly test -- --features unstable-testing)
- (cd quasi_macros && travis-cargo --only nightly test -- --features unstable-testing)
- (cd quasi_tests && travis-cargo --skip nightly test)
- (cd quasi_tests && travis-cargo --only nightly test -- --features unstable-testing)

after_success:
- (cd quasi_tests && travis-cargo --only stable coveralls --no-sudo)

env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
